# ruff: noqa: E501
"""Load a fourth held-out 30-case challenge set from organizer-supplied tables.

Expected answers are regenerated by executing the bounded standard SQL against
the official local database.  The questions are never stored as retrieval
examples, so they remain an independent evaluation set.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from psycopg.types.json import Jsonb

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.db.session import engine

DATASET_VERSION = "official-v1-challenge-v4"
SOURCE_TYPE = "official_challenge_v4"
TAG = "official_challenge_v4"


@dataclass(frozen=True)
class ChallengeCase:
    code: str
    question: str
    difficulty: str
    sql: str
    topic: str


def case(no: int, question: str, difficulty: str, sql: str, topic: str) -> ChallengeCase:
    return ChallengeCase(f"V4-{no:03d}", question, difficulty, sql.strip(), topic)


CASES: tuple[ChallengeCase, ...] = (
    case(1, "请按性别代码汇总当前去重客户数量，最多展示10组。", "simple", """
        select gender_cd, count(distinct pty_id) as customer_count
        from mart.ads_cust_info_d
        group by gender_cd order by customer_count desc, gender_cd limit 10
    """, "customer"),
    case(2, "请按客户等级代码统计当前客户数，取前10个等级。", "simple", """
        select cust_lvl_cd, count(distinct pty_id) as customer_count
        from mart.ads_cust_info_d
        group by cust_lvl_cd order by customer_count desc, cust_lvl_cd limit 10
    """, "customer"),
    case(3, "当前快照中，年龄小于35岁的去重客户有几位？", "simple", """
        select count(distinct pty_id) as customer_count
        from mart.ads_cust_info_d where cust_age < 35 limit 1
    """, "customer"),
    case(4, "按省份看客户平均年龄，列出平均年龄最高的前10个省份。", "medium", """
        select prov_name, avg(cust_age) as average_customer_age
        from mart.ads_cust_info_d
        group by prov_name order by average_customer_age desc nulls last, prov_name limit 10
    """, "customer"),
    case(5, "请按客户状态和城市联合统计当前去重客户数，展示前20组。", "complex", """
        select cust_status, city_name, count(distinct pty_id) as customer_count
        from mart.ads_cust_info_d
        group by cust_status, city_name
        order by customer_count desc, cust_status, city_name limit 20
    """, "customer"),
    case(6, "截至2026年2月28日，所有客户总资产合计是多少？", "simple", """
        select sum(coalesce(nm_tot_aset, 0) + coalesce(fc_pur_aset, 0)) as total_asset
        from mart.dws_cust_aset_d where data_dt = '20260228' limit 1
    """, "asset"),
    case(7, "截至2026年2月28日，分省汇总客户总资产，展示前10个省份。", "medium", """
        select c.prov_name, sum(coalesce(a.nm_tot_aset, 0) + coalesce(a.fc_pur_aset, 0)) as total_asset
        from mart.dws_cust_aset_d a join mart.ads_cust_info_d c on c.pty_id = a.pty_id
        where a.data_dt = '20260228'
        group by c.prov_name order by total_asset desc, c.prov_name limit 10
    """, "asset"),
    case(8, "截至2026年2月28日，按城市汇总客户现金资产，展示前10个城市。", "medium", """
        select c.city_name, sum(coalesce(a.nm_bal, 0) + coalesce(a.fc_bal, 0)) as cash_asset
        from mart.dws_cust_aset_d a join mart.ads_cust_info_d c on c.pty_id = a.pty_id
        where a.data_dt = '20260228'
        group by c.city_name order by cash_asset desc, c.city_name limit 10
    """, "asset"),
    case(9, "截至2026年3月31日，普通账户总资产合计为多少？", "simple", """
        select sum(coalesce(nm_tot_aset, 0)) as normal_total_asset
        from mart.dws_cust_aset_d where data_dt = '20260331' limit 1
    """, "asset"),
    case(10, "截至2026年3月31日，信用账户净资产合计为多少？", "simple", """
        select sum(coalesce(fc_pur_aset, 0)) as credit_total_asset
        from mart.dws_cust_aset_d where data_dt = '20260331' limit 1
    """, "asset"),
    case(11, "2026年第一季度，按币种统计交易金额，取金额最高的前10种币种。", "medium", """
        select ccy, sum(coalesce(buy_amt, 0) + coalesce(sell_amt, 0)) as trade_amount
        from mart.dwd_cust_tran_d where data_dt between '20260101' and '20260331'
        group by ccy order by trade_amount desc, ccy limit 10
    """, "trade"),
    case(12, "2026年第一季度，按客户所在城市统计交易金额，展示前10个城市。", "complex", """
        select c.city_name, sum(coalesce(t.buy_amt, 0) + coalesce(t.sell_amt, 0)) as trade_amount
        from mart.dwd_cust_tran_d t join mart.ads_cust_info_d c on c.pty_id = t.pty_id
        where t.data_dt between '20260101' and '20260331'
        group by c.city_name order by trade_amount desc, c.city_name limit 10
    """, "trade"),
    case(13, "2026年第一季度的交易费用总额是多少？", "simple", """
        select sum(coalesce(buy_fare, 0) + coalesce(sell_fare, 0)) as trade_fee
        from mart.dwd_cust_tran_d where data_dt between '20260101' and '20260331' limit 1
    """, "trade"),
    case(14, "2026年第一季度，累计交易费用达到1000元及以上的客户有多少位？", "medium", """
        select count(*) as customer_count from (
          select pty_id from mart.dwd_cust_tran_d
          where data_dt between '20260101' and '20260331'
          group by pty_id having sum(coalesce(buy_fare, 0) + coalesce(sell_fare, 0)) >= 1000
        ) fee_customers limit 1
    """, "trade"),
    case(15, "2026年第一季度，买入金额和卖出金额都大于零的客户共有多少位？", "complex", """
        select count(*) as customer_count from (
          select pty_id from mart.dwd_cust_tran_d
          where data_dt between '20260101' and '20260331'
          group by pty_id
          having sum(coalesce(buy_amt, 0)) > 0 and sum(coalesce(sell_amt, 0)) > 0
        ) bilateral_customers limit 1
    """, "trade"),
    case(16, "截至2026年2月28日，按一级产品分类统计持仓市值，展示前10个分类。", "medium", """
        select p.up_prdt_type_name, sum(coalesce(h.mkt_val, 0)) as holding_market_value
        from mart.dwd_cust_hold_d h join mart.dim_product p on p.prdt_id = h.prdt_id
        where h.data_dt = '20260228'
        group by p.up_prdt_type_name
        order by holding_market_value desc, p.up_prdt_type_name limit 10
    """, "holding"),
    case(17, "截至2026年2月28日，按二级产品分类统计持仓客户数量，展示前10类。", "medium", """
        select p.prdt_type_name, count(distinct h.pty_id) as customer_count
        from mart.dwd_cust_hold_d h join mart.dim_product p on p.prdt_id = h.prdt_id
        where h.data_dt = '20260228'
        group by p.prdt_type_name
        order by customer_count desc, p.prdt_type_name limit 10
    """, "holding"),
    case(18, "截至2026年2月28日，客户持有份额总量是多少？", "simple", """
        select sum(coalesce(hold_cnt, 0)) as holding_quantity
        from mart.dwd_cust_hold_d where data_dt = '20260228' limit 1
    """, "holding"),
    case(19, "截至2026年2月28日，至少持有3种不同产品的客户有多少位？", "complex", """
        select count(*) as customer_count from (
          select pty_id from mart.dwd_cust_hold_d where data_dt = '20260228'
          group by pty_id having count(distinct prdt_id) >= 3
        ) multi_product_customers limit 1
    """, "holding"),
    case(20, "截至2026年2月28日，按城市统计持仓市值，展示市值最高的前10个城市。", "complex", """
        select c.city_name, sum(coalesce(h.mkt_val, 0)) as holding_market_value
        from mart.dwd_cust_hold_d h join mart.ads_cust_info_d c on c.pty_id = h.pty_id
        where h.data_dt = '20260228'
        group by c.city_name order by holding_market_value desc, c.city_name limit 10
    """, "holding"),
    case(21, "2026年第一季度，客户净资金流入总额是多少？", "simple", """
        select sum(coalesce(cash_in, 0) + coalesce(tran_in, 0) + coalesce(assign_in, 0)
                   - coalesce(cash_out, 0) - coalesce(tran_out, 0) - coalesce(assign_out, 0)) as net_cash_flow
        from mart.dws_cust_fin_d where data_dt between '20260101' and '20260331' limit 1
    """, "cash_flow"),
    case(22, "2026年第一季度，按客户所在省份统计净资金流入，展示前10个省份。", "complex", """
        select c.prov_name, sum(coalesce(f.cash_in, 0) + coalesce(f.tran_in, 0) + coalesce(f.assign_in, 0)
                                 - coalesce(f.cash_out, 0) - coalesce(f.tran_out, 0) - coalesce(f.assign_out, 0)) as net_cash_flow
        from mart.dws_cust_fin_d f join mart.ads_cust_info_d c on c.pty_id = f.pty_id
        where f.data_dt between '20260101' and '20260331'
        group by c.prov_name order by net_cash_flow desc, c.prov_name limit 10
    """, "cash_flow"),
    case(23, "2026年第一季度，累计净资金流入为正的客户数量是多少？", "complex", """
        select count(*) as customer_count from (
          select pty_id from mart.dws_cust_fin_d
          where data_dt between '20260101' and '20260331'
          group by pty_id
          having sum(coalesce(cash_in, 0) + coalesce(tran_in, 0) + coalesce(assign_in, 0)
                     - coalesce(cash_out, 0) - coalesce(tran_out, 0) - coalesce(assign_out, 0)) > 0
        ) positive_flow_customers limit 1
    """, "cash_flow"),
    case(24, "2026年第一季度，按客户状态统计转账金额，展示前10个状态。", "complex", """
        select c.cust_status, sum(coalesce(f.tran_in, 0) + coalesce(f.tran_out, 0)) as transfer_amount
        from mart.dws_cust_fin_d f join mart.ads_cust_info_d c on c.pty_id = f.pty_id
        where f.data_dt between '20260101' and '20260331'
        group by c.cust_status order by transfer_amount desc, c.cust_status limit 10
    """, "cash_flow"),
    case(25, "截至2026年2月28日，按一级营业部汇总客户现金资产，展示前10个营业部。", "medium", """
        select b.up_org_name, sum(coalesce(a.nm_bal, 0) + coalesce(a.fc_bal, 0)) as cash_asset
        from mart.dws_cust_aset_d a
        join mart.ads_cust_info_d c on c.pty_id = a.pty_id
        join mart.dim_branch b on b.org_id = c.org_id
        where a.data_dt = '20260228'
        group by b.up_org_name order by cash_asset desc, b.up_org_name limit 10
    """, "asset"),
    case(26, "截至2026年2月28日，按一级营业部统计客户总资产，取前10个营业部。", "medium", """
        select b.up_org_name, sum(coalesce(a.nm_tot_aset, 0) + coalesce(a.fc_pur_aset, 0)) as total_asset
        from mart.dws_cust_aset_d a
        join mart.ads_cust_info_d c on c.pty_id = a.pty_id
        join mart.dim_branch b on b.org_id = c.org_id
        where a.data_dt = '20260228'
        group by b.up_org_name order by total_asset desc, b.up_org_name limit 10
    """, "asset"),
    case(27, "按一级营业部计算当前客户平均年龄，展示前10个营业部。", "medium", """
        select b.up_org_name, avg(c.cust_age) as average_customer_age
        from mart.ads_cust_info_d c join mart.dim_branch b on b.org_id = c.org_id
        group by b.up_org_name order by average_customer_age desc nulls last, b.up_org_name limit 10
    """, "customer"),
    case(28, "2026年第一季度，按一级产品分类汇总交易金额，展示前10个分类。", "medium", """
        select p.up_prdt_type_name, sum(coalesce(t.buy_amt, 0) + coalesce(t.sell_amt, 0)) as trade_amount
        from mart.dwd_cust_tran_d t join mart.dim_product p on p.prdt_id = t.prdt_id
        where t.data_dt between '20260101' and '20260331'
        group by p.up_prdt_type_name order by trade_amount desc, p.up_prdt_type_name limit 10
    """, "trade"),
    case(29, "2026年第一季度，按二级产品分类汇总交易金额，展示前10个分类。", "medium", """
        select p.prdt_type_name, sum(coalesce(t.buy_amt, 0) + coalesce(t.sell_amt, 0)) as trade_amount
        from mart.dwd_cust_tran_d t join mart.dim_product p on p.prdt_id = t.prdt_id
        where t.data_dt between '20260101' and '20260331'
        group by p.prdt_type_name order by trade_amount desc, p.prdt_type_name limit 10
    """, "trade"),
    case(30, "截至2026年2月28日，按币种汇总持有份额，展示前10种币种。", "medium", """
        select ccy, sum(coalesce(hold_cnt, 0)) as holding_quantity
        from mart.dwd_cust_hold_d where data_dt = '20260228'
        group by ccy order by holding_quantity desc, ccy limit 10
    """, "holding"),
)


def jsonable(value: Any) -> Any:
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    return value


def expected(cursor: Any, sql: str) -> dict[str, Any]:
    cursor.execute(sql)
    columns = [item.name for item in cursor.description]
    rows = [
        {key: jsonable(value) for key, value in zip(columns, row, strict=True)}
        for row in cursor.fetchall()
    ]
    return {"columns": columns, "rows": rows, "row_count": len(rows), "comparison": "unordered"}


def validate() -> None:
    if len(CASES) != 30 or len({item.code for item in CASES}) != 30 or len({item.question for item in CASES}) != 30:
        raise ValueError("The fourth held-out challenge set must contain 30 unique cases.")
    for item in CASES:
        sql = item.sql.lower()
        if "mart." not in sql or " limit " not in sql or ".name" in sql:
            raise ValueError(f"{item.code} is not an official, bounded, non-sensitive query.")


def main() -> None:
    validate()
    connection = engine.raw_connection()
    try:
        with connection.cursor() as cursor:
            cursor.execute(
                "update evaluation.eval_cases set is_active = false where source_type = %s",
                (SOURCE_TYPE,),
            )
            for item in CASES:
                cursor.execute(
                    """
                    insert into evaluation.eval_cases
                        (case_code, question, difficulty, scenario, expected_query_plan, expected_sql,
                         expected_result, scoring_config, dataset_version, source_type, expected_status,
                         tags, is_active)
                    values (%s, %s, %s, 'customer_marketing', %s, %s, %s, %s, %s, %s, 'completed', %s, true)
                    on conflict (case_code) do update set
                        question = excluded.question,
                        difficulty = excluded.difficulty,
                        scenario = excluded.scenario,
                        expected_query_plan = excluded.expected_query_plan,
                        expected_sql = excluded.expected_sql,
                        expected_result = excluded.expected_result,
                        scoring_config = excluded.scoring_config,
                        dataset_version = excluded.dataset_version,
                        source_type = excluded.source_type,
                        expected_status = excluded.expected_status,
                        tags = excluded.tags,
                        is_active = true,
                        updated_at = now()
                    """,
                    (
                        item.code,
                        item.question,
                        item.difficulty,
                        Jsonb({"intent": "metric_query", "scenario": "customer_marketing"}),
                        item.sql,
                        Jsonb(expected(cursor, item.sql)),
                        Jsonb({"comparison": "unordered", "require_execution": True}),
                        DATASET_VERSION,
                        SOURCE_TYPE,
                        Jsonb([TAG, "benchmark", item.topic, item.difficulty, item.code.lower()]),
                    ),
                )
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()
    print(json.dumps({"loaded_challenge_cases": len(CASES), "source_type": SOURCE_TYPE, "is_held_out": True}, ensure_ascii=False))


if __name__ == "__main__":
    main()
